# Generated by Django 4.1 on 2022-09-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_barangwatchlist_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangwatchlist',
            name='rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='barangwatchlist',
            name='watched',
            field=models.TextField(),
        ),
    ]
